# Generated by Django 5.2.17 on 2026-08-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='agent_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='watch_folder',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
