# Generated by Django 5.2.17 on 2026-08-11 06:00

import django.db.models.deletion
import photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=photos.models.event_photo_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=photos.models.event_thumb_path)),
                ('face_encodings', models.JSONField(blank=True, default=list)),
                ('processed', models.BooleanField(default=False)),
                ('face_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
