# Generated by Django 5.2.17 on 2026-08-11 06:00

import django.db.models.deletion
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=guests.models.selfie_upload_path)),
                ('face_encoding', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('task_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_uploads', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('guest_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='guests.guestupload')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='photos.eventphoto')),
            ],
            options={
                'ordering': ['confidence'],
                'unique_together': {('guest_upload', 'photo')},
            },
        ),
    ]
